config/routes.rb
Rails.application.routes.draw do
  # get 'events/new'
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :events
  resources :attendances

  get 'sign_in' => 'sessions#new', as: 'sign_in'
  get 'sign_out' => 'sessions#destroy', as: 'sign_out'
  get 'sign_up' => 'users#new', as: 'sign_up'

  get '/inviteUsers/:event_id' => 'users#index', as: :inviteUsers
  get '/invite/:user_id/:event_id' => 'users#invite_user', as: :invite
  get '/attend/:user_id/:event_id' => 'users#attend_events', as: :attend
  get '/withdraw/:user_id/:event_id' => 'users#withdraw_events', as: :withdraw
  get '/cancel/:user_id/:event_id' => 'users#cancel_invite_user', as: :cancel

  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# root to: 'events#index'
#   resources :users, only: %i[new create show]
#   resources :events, only: %i[new create show index]
#   get '/attend/:user_id/:event_id' => 'users#attend_events', as: :attend
#   get '/withdraw/:user_id/:event_id' => 'users#withdraw_events', as: :withdraw
#   get '/inviteUsers/:event_id' => 'users#index', as: :inviteUsers
#   get '/invite/:user_id/:event_id' => 'users#invite_user', as: :invite
#   get '/cancel/:user_id/:event_id' => 'users#cancel_invite_user', as: :cancel
#   get '/login' => 'sessions#new'
#   post '/login' => 'sessions#create'
#   get '/logout' => 'sessions#destroy'

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :user_id, class_name: 'Event'
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances, class_name: 'Event'

  validates :name, length: { minimum: 3, maximum: 16 }
  validates :name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :logged_in?, only: %i[attend_events withdraw_events invite_user cancel_invite_user]

  def index
    @users = User.where('id != ?', current_user.id).order('name ASC')
    @event = Event.find(params[:event_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was Successfully created' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @created_event = @user.events
    @upcoming = Event.upcoming.select do |event|
      event.attendances.where('status = ?', true).where('attendee_id = ?', @user.id)
    end
    @past = Event.past.select do |event|
      event.attendances.where('status = ?', true).where('attendee_id = ?', @user.id)
    end
  end

  def attend_events
    @user = User.find(params[:user_id])
    @event = Event.find(params[:event_id])
    @attendance = @user.attendances.where('attended_event_id = ?', @event.id).first
    @attendance.status = true
    @attendance.save
    flash.notice = 'Invitation Accepted!'
    redirect_to '/'
  end

  def withdraw_events
    @user = User.find(params[:user_id])
    @event = Event.find(params[:event_id])
    @attendance = @user.attendances.where('attended_event_id = ?', @event.id).first
    @attendance.status = false
    @attendance.save
    flash.notice = 'Event Cancelled!'
    redirect_to '/'
  end

  def invite_user
    @user = User.find(params[:user_id])
    @event = Event.find(params[:event_id])
    @user.attendances.create(attended_event: @event)
    flash.notice = "Invitation sent to #{@user.name} !"
    redirect_to "/inviteUsers/#{@event.id}"
  end

  def cancel_invite_user
    @user = User.find(params[:user_id])
    @event = Event.find(params[:event_id])
    @user.attended_events.delete(@event)
    flash.notice = "Invitation cancelled for #{@user.name} !"
    redirect_to "/inviteUsers/#{@event.id}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user; end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def invitation(user)
    if invited?(user, @event.id) && attended?(user, @event.id)
      content_tag(:p, 'Invitation accepted', class: 'font-weight-bold text-success py-1 px-4')
    elsif invited?(user, @event.id) && attended?(user, @event.id) != true
      content_tag(:div,
                  link_to('Cancel invitation', cancel_path(user_id: user.id, event_id: @event.id),
                          class: 'py-1 px-4 text-center rounded nav-link border border-danger text-danger'))
    else
      content_tag(:div,
                  link_to('Invite', invite_path(user_id: user.id, event_id: @event.id),
                          class: 'btn btn-primary text-center rounded nav-link py-1 px-4'))
    end
  end
end

app/views/users/index.html.erb
<div class="main-invite container-fluid p-3 d-flex justify-content-center w-50">
    <h2>Invite User for the <span class="text-primary"><%= @event.title %> </span> Event!!</h2>
</div>
<div class=" user-invitation p-3 align-item-center bg-light w-50">
    <% @users.each do |user| %>
        <div class="d-flex p-3 m-3 align-items-center justify-content-between">
            <div class="mx-2 font-weight-bold w-25">
                <%= user.name %></td>
            </div>
            <div>
                <%= invitation(user) %>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="box main my-5 mx-auto align-items-center d-flex flex-column border p-4 container w-25">
    <h1 class="text-primary font-weight-bold">Sign Up</h1>
    <div class="login-field">
        <%= form_with model: @user, local: true do |f| %>
            <% if @user.errors.any? %>
                <div id="error_explanation">
                    <h4 class="text-danger text-center"><%= pluralize(@user.errors.count, "error") %> Error occured:</h4>

                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="form-group">
                <%= f.label :name, class: "form_label" %>
                <%= f.text_field :name, class: "form-control", placeholder: 'User Name'   %>
            </div>
            <div class="form-group">
                <%= f.submit 'Sign Up', class: 'btn btn-primary' %>
            </div>
            <div>
                <%= link_to 'Log In', sign_in_path, class: '' %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="author d-flex flex-column justify-content-center align-items-center h2 text-capitalize p-3 bg-light">
    <img src="https://thewritelife.com/wp-content/uploads/2014/12/how-to-become-a-technical-writer.jpg" alt="author" class="author-img">
    <a href="" class="mt-3 text-decoration-none">
        <%= @user.name %>
    </a>
</div>

<br >

<div class="card box p-3 mb-3 float-right col-4 p-3 m-3">

  <h1 class="text-uppercase text-primary justify-content-center d-flex  h4">Attended Events</h1>

  <div aria-labelledby="nav-profile-tab">
        <h3 class="h5 text-capitalize">Upcoming Events</h3>
              <% @upcoming.each do |event| %>
                <div class="d-flex flex-column my-3">
                  <%= link_to event.title, event_path(event), class: "text-primary font-weight-bold h5 text-decoration-none"  %>
                  <span class="text-uppercase text-danger mt-n2"><%= event.date %></span>
                </div>                    
              <% end %>
              <hr>
  </div>

   <div aria-labelledby="nav-profile-tab border-top">
        <h3 class="h5 text-capitalize">past Events</h3>
              <% @past.each do |event| %>
                    <div class="d-flex flex-column my-3">
                        <%= link_to event.title, event_path(event), class: "text-primary font-weight-bold h5 text-decoration-none" %>

                      <span class="text-uppercase text-danger mt-n2"><%= event.date %></span>
                      </div>
              <% end %>
  </div>


</div>


<div class="created-event clearfix float-left col-7 p-3 m-3 bg-light">
    <h1 class="text-uppercase text-primary ml-5 mb-n3 h3 font-weight-bold">Created Events</h1>
        <div class="grid-post">
        <% if @created_event.any? %>
            <% @created_event.each do |e| %>
              
                  <div class="card box"> 
                      <div class="card-body">
                          <div class="card-title">
                              <%= link_to e.title, event_path(e), class: 'h4 text-uppercase text-decoration-none post-title' %>
                          </div>
                          <div class="card-text post-body">
                              <%= e.description %>
                          </div>
                      </div>
                  </div>
              
            <% end %>
        <% else %>
            <div class="d-flex flex-column p-3 m-3">
                <p>User has Not Created any Events</p>
                <%= link_to "Create Event", new_event_path, class: "btn btn-primary w-75"  %>
            </div>
        <% end %>
        </div>
</div>