config/routes.rb
Rails.application.routes.draw do
  # get 'events/new'
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :events
  resources :attendances

  get 'sign_in' => 'sessions#new', as: 'sign_in'
  get 'sign_out' => 'sessions#destroy', as: 'sign_out'
  get 'sign_up' => 'users#new', as: 'sign_up'

  get '/inviteUsers/:event_id' => 'users#index', as: :inviteUsers
  get '/invite/:user_id/:event_id' => 'users#invite_user', as: :invite
  get '/attend/:user_id/:event_id' => 'users#attend_events', as: :attend
  get '/withdraw/:user_id/:event_id' => 'users#withdraw_events', as: :withdraw
  get '/cancel/:user_id/:event_id' => 'users#cancel_invite_user', as: :cancel

  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# root to: 'events#index'
#   resources :users, only: %i[new create show]
#   resources :events, only: %i[new create show index]
#   get '/attend/:user_id/:event_id' => 'users#attend_events', as: :attend
#   get '/withdraw/:user_id/:event_id' => 'users#withdraw_events', as: :withdraw
#   get '/inviteUsers/:event_id' => 'users#index', as: :inviteUsers
#   get '/invite/:user_id/:event_id' => 'users#invite_user', as: :invite
#   get '/cancel/:user_id/:event_id' => 'users#cancel_invite_user', as: :cancel
#   get '/login' => 'sessions#new'
#   post '/login' => 'sessions#create'
#   get '/logout' => 'sessions#destroy'

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  has_many :attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :attendances, class_name: 'User'

  scope :upcoming, -> { where('date >= ?', Date.today) }
  scope :past, -> { where('date < ?', Date.today) }

  validates :title, length: { minimum: 3, maximum: 90 }
  validates_presence_of :title, :description, :date, :location
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, except: [:index]

  def index
    @events = Event.all
    @upcomming_events = Event.upcoming
    @past_events = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendances = Attendance.where('status = ?', true).where('attended_event_id = ?', @event.id)
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :location, :creator_id)
  end
end

app/helpers/events_helper.rb
# rubocop:disable Metrics/CyclomaticComplexity
# rubocop:disable Metrics/PerceivedComplexity
# rubocop:disable Style/SafeNavigation

module EventsHelper
  def invitation_people
    accept = 'You have been invited. Accept Invitation'
    if current_user && current_user.events.exists?(@event.id)
      content_tag(:div,
                  link_to('Invite people', inviteUsers_path(@event), class: 'btn btn-primary p-2 text-center rounded'))
    elsif current_user && invited?(current_user, @event.id) && attended?(current_user, @event.id)
      content_tag(:div,
                  link_to('Withdraw', withdraw_path(user_id: current_user.id, event_id: @event.id),
                          class: 'btn btn-primary p-2 text-center rounded'))
    elsif current_user && invited?(current_user, @event.id) && attended?(current_user, @event.id) != true
      content_tag(:div,
                  link_to(accept.to_s, attend_path(user_id: current_user.id, event_id: @event.id),
                          class: 'btn btn-primary p-2 text-center rounded'))
    else
      content_tag(:p, 'You must be invited to attend this Event', class: 'text-danger')
    end
  end
end

# rubocop:enable Metrics/CyclomaticComplexity
# rubocop:enable Metrics/PerceivedComplexity
# rubocop:enable Style/SafeNavigation

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |f| %>

    <div class="form-group">
        <%= f.label :title, class: "form_label" %>
        <%= f.text_field :title, class: "form-control", placeholder: 'Title'   %>
    </div>

    <div class="form-group">
        <%= f.label :description, class: "form_label" %>
        <%= f.text_area :description, class: "form-control"   %>
    </div>

    <div class="form-group ">
        <%= f.label :date, class: "form_label" %>
        <%= f.datetime_select :date, class: "form-control datepicker"  %>
    </div>

    <div class="form-group">
        <%= f.label :location, class: "form_label" %>
        <%= f.text_field :location, class: "form-control"  %>
    </div>

    <div class="form-group">
        <%= f.submit 'Create Event', class: 'btn btn-primary' %>
    </div>

<% end %>

app/views/events/_past-events.html.erb
<div class="grid-post">
    <% @past_events.each do |e| %>
        <div class="card box bg-light">
            <div class="card-body">
                <div class="card-title">
                    <%= link_to e.title, event_path(e), class: 'h4 text-uppercase text-decoration-none post-title mb-0' %>
                <small>
                    <%= e.date %>
                </small>
                </div>
                <div class="card-text post-body">
                    <%= e.description %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/events/_upcoming-events.html.erb
<div class="grid-post">
    <% @upcomming_events.each do |e| %>
        <div class="card box">
            <div class="card-body">
                <div class="card-title ">
                    <%=link_to e.title, event_path(e), class: 'mb-0 h4 text-uppercase text-decoration-none post-title' %>
                    <small>
                    <%= e.date %>
                </small>
                </div>
                <div class="card-text post-body">
                    <%= e.description %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/events/index.html.erb
<div class="upcoming-events p-3">
    <h2 class="text-Uppercase text-secondary ml-5 mb-n3">Upcoming Events</h2>
    <% if @upcomming_events %>
        <%= render 'upcoming-events' %>
    <% end %>

</div>
<div class="past-events p-3">

    <h2 class="text-Uppercase text-secondary ml-5 mb-n3">Past Events </h2>

    <% if @past_events %>
       <%= render 'past-events' %>
    <% end %>
</div>

app/views/events/new.html.erb
<div class="box main my-5 mx-auto align-items-center d-flex flex-column border p-4 container w-50">
    <h1 class="text-primary font-weight-bold">Create Event</h1>
    <hr>
    <div class="login-field">
        <%= render 'form' %>
    </div>
</div>

app/views/events/show.html.erb
<img src="https://assets.simpleviewinc.com/simpleview/image/fetch/c_limit,q_75,w_1200/https://assets.simpleviewinc.com/simpleview/image/upload/crm/sanmateoca/shutterstock_61104537504_8ef67d97-5056-a36a-0b9f5fc892eae781.jpg" alt="img" class="card-img-top img-show">
<div class="main-event p-5 container">

    <div class="right col-4 float-right ml-2">
        <div class="card box p-3 mb-3">
            <div class="date d-flex">
                <span class="h3">
                    <i class="far fa-calendar-check text-primary"></i>
                    <%= @event.date %>
                </span>  
            </div>
            <div class="date my-3"> 
                <span>
                    <i class="fas fa-map-marker-alt h-3 text-primary"></i>    
                    <%= @event.location %>
                </span>   
            </div>

            <div class="join-event">
                <%= invitation_people %>
            </div>
        </div>

        <div class="attendees card box p-3 mb-3">
            <h3 class="text-uppercase font-weight-bold">List of attendees</h3>
                <div class="list-attendees text-primary">
                    <ul class="list-unstyled mt-1">
                            <% @attendances.each do |attend| %>
                                <li> 
                                    <%= link_to attend.attendee.name, user_path(attend.attendee), class: "text-primary text-capitalize h5" %>
                                    <hr>
                                </li>
                            <% end %>
                    </ul>
                </div>
        </div>

    </div>

    <div class="left col-7">

        <div class="text-primary text-uppercase h3 font-weight-bold ">
            <%= @event.title %>
        </div>
        
        <div class="text">
            <h3 class="mt-3 mb-1 h5">About Event</h3>
            <%= @event.description %>
        </div>

        <hr>
        <div class="my-3 d-flex align-items-center justify-content-between">
            
            <%= link_to "Back", events_path, class: "text-primary h5 "%>
            <p class="h5 text-dark align-items-center mb-0"> <%= @event.creator.name %>
            <i class="fas fa-user-circle"></i>
            </p>
        </div>

    </div>
</div>